name: Deploy GrabbableEyewear to Cloudflare Pages

on:
  push:
    branches:
      - main
    paths-ignore:
      - README.md
      - '.**'
      - '.**/**'
      - '!.github/workflows/deploy.yml'
  workflow_dispatch:

env:
  CLOUDFLARE_PROJECT_NAME: grabbable-eyewear-doc

jobs:
  build:
    permissions:
      contents: read
    runs-on: ubuntu-latest
    steps:
      - name: Checkout your repository using git
        uses: actions/checkout@v4
      - name: Install, build, and upload your site
        uses: withastro/action@v3
        with:
         package-manager: pnpm

  deploy:
    permissions:
      contents: read
      deployments: write
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: cloudflare-pages
      url: ${{ steps.deployment.outputs.deployment-url }}
    steps:
      - name: Download built files
        uses: actions/download-artifact@v4
        with:
          name: github-pages
          path: dist
      - name: Deploy to Cloudflare Pages
        id: deployment
        uses: cloudflare/wrangler-action@v3
        with:
          command: pages deploy dist --project-name=${{ env.CLOUDFLARE_PROJECT_NAME }}
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
